---
label: Product Page Simple
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: list
  name: tags
  label: tags
- type: list
  name: categories
  label: categories
- type: image_gallery
  name: images
  label: images
- type: file
  name: thumbnailImage
  label: thumbnailImage
- type: text
  name: comparePrice
  label: comparePrice
- type: text
  name: actualPrice
  label: actualPrice
- type: boolean
  name: inStock
  label: inStock
- type: field_group
  name: options
  label: options
- type: list
  name: variants
  label: variants
- name: instock
  type: boolean
  label: inStock
  hidden: true
