---
label: Product Page Simple
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- name: tags
  type: tag_list
  default: []
  label: tags
- type: list
  name: categories
  label: categories
- type: image_gallery
  name: images
  label: images
- type: file
  name: thumbnailImage
  label: thumbnailImage
- type: text
  name: actualPrice
  label: actualPrice
- type: boolean
  name: inStock
  label: inStock
- name: sku
  type: text
  config:
    required: false
  label: sku
  description: 'Unique name/number, no spaces or special characters. '
- name: description
  type: text
  config:
    required: false
  label: description
  description: Basic description of product.
- name: weight
  type: number
  label: weight
  description: weight in grams
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
pages:
- content/products/cheese-grater.md
- content/products/fuse-box.md
